services:
  mysql:
    image: mysql:8.4
    platform: linux/amd64  
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    profiles:
      - mysql

  postgres:
    image: postgres:16.3
    platform: linux/amd64 Ö¿
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    profiles:
      - postgres

  jenkins:
    build: ./jenkins/master
    image: jenkins-jb/master:1.0
    container_name: jenkins
    ports:
      - '8081:8080'
      - '50000:50000'
    networks:
      - jb

  jenkins-slave:
    build: ./jenkins/slave
    image: jenkins-jb/slave:1.0
    restart: always
    environment:
      - 'JENKINS_URL=http://jenkins:8081'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
      - ./volume:/home/jenkins  
    networks:
      - jb
    depends_on:
      - jenkins

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    environment:
      - SONARQUBE_JDBC_USERNAME=admin
      - SONARQUBE_JDBC_PASSWORD=qube777
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonarqube
    ports:
      - "9000:9000"
    networks:
      - jb

networks:
  jb: