services:
  mysql:
    image: mysql:8.4
    platform: linux/amd64  # Specify the platform
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    profiles:
      - mysql

  postgres:
    image: postgres:16.3
    platform: linux/amd64  # Specify the platform
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    profiles:
      - postgres

  jenkins:
    build: .
    platform: linux/amd64  # Specify the platform
    image: jenkins-jb/main:1.0
    container_name: jenkins-main
    ports:
      - '8081:8080'
      - '50000:50000'
    networks:
      - jb

  jenkins-slave:
    build: ./slave
    platform: linux/amd64  # Specify the platform
    image: jenkins-jb/slave:1.0
    container_name: jenkins-slave
    restart: always
    environment:
      - 'JENKINS_URL=http://jenkins:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volume:/home/jenkins
    networks:
      - jb
    depends_on:
      - jenkins

networks:
  jb:
